-- ============================================================
--  WIM - Windows Integrated Modular Neovim
--  init.lua — Entry point
-- ============================================================

-- Bootstrap lazy.nvim (plugin manager)
local lazypath = vim.fn.stdpath("data") .. "\\lazy\\lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git", "clone", "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

-- Load WIM modules in order
require("wim.options")   -- core vim options
require("wim.keymaps")   -- keybindings
require("wim.autocmds")  -- auto commands

-- Load shell config if generated by installer
local shell_config = vim.fn.stdpath("config") .. "\\lua\\wim\\shell.lua"
if vim.loop.fs_stat(shell_config) then
    dofile(shell_config)
end

-- Load plugins via lazy.nvim
require("lazy").setup("wim.plugins", {
    defaults = { lazy = true },
    install  = { colorscheme = { "catppuccin", "habamax" } },
    checker  = { enabled = true, notify = false },
    change_detection = { notify = false },
    performance = {
        rtp = {
            -- Disable unused built-in plugins to keep startup fast
            disabled_plugins = {
                "gzip", "matchit", "matchparen",
                "netrwPlugin", "tarPlugin", "tohtml",
                "tutor", "zipPlugin",
            },
        },
    },
})
